SearchEngine/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SearchEngine.BLL.DTO;
using SearchEngine.BLL.Interfaces;
using SearchEngine.WEB.Interfaces;
using SearchEngine.BLL.StatisticModels;

namespace SearchEngine.WEB.Controllers
{
    public class DocumentController : Controller
    {
        private IServiceFactory _serviceFactory;
        private IFileService _fileService;
        private ISearchService _searchService;

        public DocumentController(IServiceFactory serviceFactory, IFileService fileService, ISearchService searchService)
        {
            _serviceFactory = serviceFactory;
            _fileService = fileService;
            _searchService = searchService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(List<IFormFile> files)
        {
            if (!files.Any())
            {
                return BadRequest();
            }

            try
            {
                foreach (IFormFile file in files)
                {
                    await SaveFileWithTermsAsync(file);
                }

                await _serviceFactory.TermService.CalculateWeightsAsync();

                _serviceFactory.CommitChanges();
            }
            catch
            {
                _serviceFactory.RollbackChanges();

                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok();
        }

        public async Task<IActionResult> Search(string query)
        {
            if (String.IsNullOrEmpty(query))
            {
                return BadRequest();
            }

            IEnumerable<KeyValuePair<string, int>> queryWordsWithOccurrences = _serviceFactory.TermService.GetTermsWithOccurrences(query);

            IEnumerable<DocumentDTO> documentDTOs = await _serviceFactory.DocumentService
                .GetDocumentsWithQueryWord(queryWordsWithOccurrences.Select(x => x.Key));

            IEnumerable<SearchResultModel> searchResults = await _searchService.Search(documentDTOs, queryWordsWithOccurrences.Select(x => x.Key));

            SearchMetricModel metricModel = await CreateMetricModelForSearchResults(searchResults);

            _serviceFactory.CommitChanges();

            return Ok(new {
                searchResults = searchResults.OrderByDescending(r => r.DocumentQuerySimilarity),
                metrics = metricModel
            });
        }

        public async Task<IActionResult> Show(string publicId)
        {
            if (String.IsNullOrEmpty(publicId))
            {
                return BadRequest();
            }

            DocumentDTO documentDTO = await _serviceFactory.DocumentService.GetByPublicIdAsync(publicId);
            if(documentDTO == null)
            {
                return NotFound();
            }

            string fileContent = await _fileService.GetContent(documentDTO.Location);

            return Ok(fileContent);
        }

        private async Task SaveFileWithTermsAsync(IFormFile file)
        {
            string filePath = await _fileService.Save(file);
            string fileContent = await _fileService.GetContent(filePath);

            IEnumerable<KeyValuePair<string, int>> termsWithOccurrences = _serviceFactory.TermService.GetTermsWithOccurrences(fileContent);

            DocumentDTO documentDTO = new DocumentDTO
            {
                PublicId = Guid.NewGuid().ToString(),
                Title = file.FileName,
                Location = filePath
            };
            int documentId = await _serviceFactory.DocumentService.CreateAsync(documentDTO);

            await _serviceFactory.TermService.CreateDocumentTermsAsync(termsWithOccurrences, documentId);
        }

        private async Task<SearchMetricModel> CreateMetricModelForSearchResults(IEnumerable<SearchResultModel> searchResults)
        {
            SearchMetricModel metricModel = new SearchMetricModel();
            if (searchResults.Count() > 0)
            {
                int numberOfSearchResults = searchResults.Count();
                metricModel.NumberOfRelevantResults = numberOfSearchResults;

                int numberOfSavedDocuments = await _serviceFactory.DocumentService.Count();
                metricModel.NotIncludedNotRelevantResults = numberOfSavedDocuments - numberOfSearchResults;
            }

            return metricModel;
        }

        protected override void Dispose(bool disposing)
        {
            _serviceFactory.Dispose();
            base.Dispose(disposing);
        }
    }
}

SearchEngine/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using SearchEngine.BLL.DTO;
using SearchEngine.BLL.Interfaces;
using SearchEngine.BLL.StatisticModels;
using SearchEngine.Common;
using SearchEngine.WEB.Interfaces;

namespace SearchEngine.WEB.Controllers
{
    public class LanguageController : Controller
    {
        private IServiceFactory _serviceFactory;
        private IFileService _fileService;

        public LanguageController(IServiceFactory serviceFactory, IFileService fileService)
        {
            _serviceFactory = serviceFactory;
            _fileService = fileService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(List<IFormFile> files, Language language)
        {
            if (!files.Any())
            {
                return BadRequest();
            }

            try
            {
                foreach (IFormFile file in files)
                {
                    await SaveFileAndDefineLanguageAsync(file, language);
                }

                _serviceFactory.CommitChanges();
            }
            catch
            {
                _serviceFactory.RollbackChanges();

                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> DefineLanguage([FromForm]List<IFormFile> files)
        {
            ICollection<LanguageDefinitionModel> languageDefinitionModels = new List<LanguageDefinitionModel>();

            if (!files.Any())
            {
                return BadRequest();
            }

            try
            {
                foreach (IFormFile file in files)
                {
                    Language? language = null;
                    LanguageDefinitionModel languageDefinitionModel = await SaveFileAndDefineLanguageAsync(file, language);

                    languageDefinitionModel.OrderNgrams();

                    languageDefinitionModels.Add(languageDefinitionModel);
                }

                _serviceFactory.CommitChanges();
            }
            catch
            {
                _serviceFactory.RollbackChanges();

                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return new ViewAsPdf(languageDefinitionModels);
        }

        public async Task<IActionResult> CompareNgrams(string specifiedLanguageDocumentPublicId, string testDocumentPublicId)
        {
            LanguageDefinitionModel languageDefinitionModel = new LanguageDefinitionModel();

            DocumentDTO specifiedLanguageDocumentDTO = await _serviceFactory.DocumentService
                .GetByPublicIdWithNgramsAsync(specifiedLanguageDocumentPublicId);

            DocumentDTO testDocumentDTO = await _serviceFactory.DocumentService.GetByPublicIdWithNgramsAsync(testDocumentPublicId);

            DocumentLanguageModel documentLanguageModel = _serviceFactory.NgramService
                .GetDocumentLanguageModel(specifiedLanguageDocumentDTO, testDocumentDTO);

            languageDefinitionModel.UnrecognizedLanguageDocumentDTO = testDocumentDTO;
            languageDefinitionModel.DocumentLanguageModels.Add(documentLanguageModel);

            languageDefinitionModel.OrderNgrams();

            return new ViewAsPdf(languageDefinitionModel);
        }

        private async Task<LanguageDefinitionModel> SaveFileAndDefineLanguageAsync(IFormFile file, Language? language)
        {
            LanguageDefinitionModel languageDefinitionModel = null;

            string filePath = await _fileService.Save(file, ".html");
            string xPathSelector = "(//div[contains(@class,'content')])[1]";
            string fileContent = await _fileService.ParseHtmlContent(filePath, xPathSelector);

            bool removeStopwords = false;
            IEnumerable<string> termOccurrences = _serviceFactory.TermService
                .GetTermsWithOccurrences(fileContent, removeStopwords)
                .Select(t => t.Key);

            IEnumerable<NgramDTO> ngramDTOs = _serviceFactory.NgramService.GetNgrams(termOccurrences);

            DocumentDTO documentDTO = new DocumentDTO
            {
                PublicId = Guid.NewGuid().ToString(),
                Title = file.FileName,
                Location = filePath,
                NgramDTOs = ngramDTOs.ToList()
            };

            if (language == null)
            {
                languageDefinitionModel = await _serviceFactory.NgramService.DefineLanguageWithStatisticsAsync(documentDTO);

                // Use alphabet service only to show the way it works.
                languageDefinitionModel.AlphabetLanguageModel = _serviceFactory.AlphabetService.DefineLanguageWithStatistics(fileContent);

                language = languageDefinitionModel.Language;
            }
            documentDTO.Language = (Language)language;

            int documentId = await _serviceFactory.DocumentService.CreateAsync(documentDTO);

            await _serviceFactory.NgramService.CreateDocumentNgramsAsync(ngramDTOs, documentId);

            return languageDefinitionModel;
        }
    }
}

SearchEngine/Views/Language/CompareNgrams.cshtml
@using SearchEngine.BLL.StatisticModels;
@using SearchEngine.BLL.DTO;
@using System.Linq;

@model LanguageDefinitionModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Compare ngrams";
    DocumentLanguageModel documentLanguageModel = Model.DocumentLanguageModels.First();
}

<div class="ngram-comparison-container">
    <table class="gridtable">
        <caption>@documentLanguageModel.SpecifiedLanguageDocumentDTO.Title</caption>
        <tr>
            <th>Specified language document</th>
        </tr>

        @foreach (NgramDTO ngramDTO in documentLanguageModel.SpecifiedLanguageDocumentDTO.NgramDTOs)
        {
            <tr>
                <td>@ngramDTO.Value : @ngramDTO.NumberOfOccurrences</td>
            </tr>
        }
    </table>

    <table class="gridtable">
        <caption>@Model.UnrecognizedLanguageDocumentDTO.Title</caption>
        <tr>
            <th>Test document</th>
            <th>Ngram distances</th>
        </tr>

        @for (int index = 0; index < Model.UnrecognizedLanguageDocumentDTO.NgramDTOs.Count(); index++)
        {
            NgramDTO ngramDTO = Model.UnrecognizedLanguageDocumentDTO.NgramDTOs.ElementAt(index);

            <tr>
                <td>@ngramDTO.Value : @ngramDTO.NumberOfOccurrences</td>
                <td>Ngram distance : @documentLanguageModel.NgramDistances.ElementAt(index)</td>
            </tr>
        }
    </table>
</div>

SearchEngine/Views/Language/DefineLanguage.cshtml
@using System.Collections.Generic;
@using SearchEngine.BLL.StatisticModels;
@using SearchEngine.Common;

@model ICollection<LanguageDefinitionModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Define language";
}

@foreach (LanguageDefinitionModel languageDefinitionModel in Model)
{
    AlphabetLanguageModel alphabetLanguageModel = languageDefinitionModel.AlphabetLanguageModel;


    <h3>@languageDefinitionModel.UnrecognizedLanguageDocumentDTO.Title</h3>
    <p>Language: @languageDefinitionModel.Language</p>
    @Html.ActionLink("Show", "Show", "Document", new { publicId = languageDefinitionModel.UnrecognizedLanguageDocumentDTO.PublicId })
    <br />

    <div class="language-definition-container">
        <table class="gridtable">
            <caption>Alphabet method</caption>
            <tr>
                <th>Number of span character matches</th>
                <th>Span lang coefficient</th>
                <th>Number of eng character matches</th>
                <th>Eng lang coefficient</th>
            </tr>
            <tr>
                <td>
                    @(languageDefinitionModel.Language == Language.English ? 0 : alphabetLanguageModel.NumberOfSpanCharacterMatches)
                </td>
                <td>
                    @(languageDefinitionModel.Language == Language.English ? 0 : alphabetLanguageModel.SpanAlphabetCoefficient)
                </td>
                <td>
                    @(languageDefinitionModel.Language == Language.Spanish ? 0 : alphabetLanguageModel.NumberOfEngCharacterMatches)
                </td>
                <td>
                    @(languageDefinitionModel.Language == Language.Spanish ? 0 : alphabetLanguageModel.EngAlphabetCoefficient)
                </td>
            </tr>

        </table>

        <table class="gridtable">
            <caption>Ngram method</caption>
            <tr>
                <th>Out of place measure</th>
                <th>Test document</th>
                <th></th>
            </tr>

            @foreach (DocumentLanguageModel documentLanguageModel in languageDefinitionModel.DocumentLanguageModels)
            {
                <tr>
                    <td>@documentLanguageModel.OutOfPlaceMeasure</td>
                    <td>
                        @Html.ActionLink(documentLanguageModel.SpecifiedLanguageDocumentDTO.Title, "Show", "Document",
                            new {publicId = documentLanguageModel.SpecifiedLanguageDocumentDTO.PublicId})
                    </td>
                    <td>
                        @Html.ActionLink("Compare ngrams", "CompareNgrams", "Language",
                            new {
                                specifiedLanguageDocumentPublicId = documentLanguageModel.SpecifiedLanguageDocumentDTO.PublicId,
                                testDocumentPublicId = languageDefinitionModel.UnrecognizedLanguageDocumentDTO.PublicId
                            })
                    </td>
                </tr>
            }

        </table>
    </div>
}

SearchEngine/Views/Language/Index.cshtml
@using SearchEngine.Common;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Index";
}

<form method="post" id="documentsUploadFormToCreateNGrams">
    @Html.AntiForgeryToken()

    <label>
        Upload one or more files to create language NGrams:
        <input type="file" id="fileInputToCreateNGrams" name="files" multiple />
    </label>
    <br />
    @Html.DropDownList("language", Html.GetEnumSelectList<Language>(), "Select Language", new { @id = "languageSelectToCreateNGrams", @class = "" })
    <br />
    <input type="submit" value="Upload" class="submit-button" />
</form>

<div id="documentsUploadAnimationElement" class="hidden">
    <img src="@Url.Content("~/images/loading.gif")" alt="Uploading..." />
</div>

<div id="uploadResultsContainer" class="hidden">

</div>

<form method="post" action="@Url.Action("DefineLanguage", "Language")" enctype="multipart/form-data" id="documentsUploadFormToDefineLanguage">

    <label>
        Upload one or more files to define their language:
        <input type="file" name="files" multiple />
    </label>
    <br/>
    <input type="submit" value="Upload" class="submit-button" />
</form>

@section Scripts {
    <!--TODO: change to bundle-->
    <script type="module" src="/js/elements-ids.js"></script>
    <script type="module" src="/js/form-fields.js"></script>
    <script type="module" src="/js/routes.js"></script>
    <script type="module" src="/js/pages/common.js"></script>
    <script type="module" src="/js/pages/define-language.js"></script>
}